language: cpp
compiler: gcc

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # SLOCcount
  - sudo apt-get install sloccount

script: 
  - qmake
  - make
  - ./love --help
  - ./love --about
  - ./love --help
  - ./love --version
  # cppcheck
  - cppcheck --quiet --error-exitcode=0 . 
  # Call OCLint
  - ./do_oclint
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov
  # Get my folder
  - my_github=${PWD##*/}  
  # SLOCcount
  - cd ..; sloccount --overhead 1 --personcost 22614 $my_github; cd $my_github

after_success:
  - bash <(curl -s https://codecov.io/bash)
